### PR TITLE
use core::error::Error for no_std support and bump MSRV to 1.81

### LINKED ISSUE #428: Support Error in no_std
core::error::Error was added in 1.81. It would be nice if hecs errors implemented it so we could benefit from using "?" operator in no_std environments. I don't know if this would require a msrv bump or if just adding a feature flag would be enough.

https://blog.rust-lang.org/2024/09/05/Rust-1.81.0/#what-s-in-1-81-0-stable

### PR DESCRIPTION
**Pull request by djsell**
Resolves #428

### CODE REVIEW

File: src/world.rs [hunk 1]
```diff
@@ -7,8 +7,7 @@ use spin::Mutex;
 
 use core::{fmt, ptr};
```
Comment (Ralith) [inline src/world.rs]: style nit
```suggestion
```

**Comment by djsell** [comment]
Fixed the formatting. Sorry about that.

**Comment by djsell** [comment]
Fixed the lint issue. As a side note, is there a guide to contributing that I missed? Would be helpful to know what to check ahead of time. I took a peek at the workflow yml this time. 😅

**Review by Ralith — APPROVED** [review]

**Comment by Ralith** [comment]
No, though there's nothing really exotic there -- just format and clippy.
