### PR TITLE
Fix query_mut permitting unsound double-borrows

### LINKED ISSUE #161: Unsound component access using mutable queries
The following test case shows how mutable queries can be used to alias the same component value via a shared reference and a mutable reference:
```
#[test]
fn unsound_component_access_using_mutable_queries() {
    let mut world = World::new();
    world.spawn((23,));
    world.spawn((42,));

    for (_, (i, m)) in world.query_mut::<(&i32, &mut i32)>() {
        let o = *i;
        *m = 0;
        let n = *i;
        assert_eq!(o, n);
    }
}
```

I think checking the internal consistency of a `Fetch` instance is required to avoid this. Since the relevant information is known at compile time, I also think that this should be possible without runtime overhead, probably via the tuple fetch combinator and the derive macro.

### PR DESCRIPTION
**Pull request by Ralith**
Fixes #161.

Not a huge fan of how this complicates `Fetch`, but it fixes the unsoundness and has no overhead in practice.

### CODE REVIEW

**Comment by Ralith** [comment]
cc @adamreichold

File: src/query.rs [hunk 1]
```diff
@@ -508,6 +533,17 @@ pub struct QueryMut<'q, Q: Query> {
 
 impl<'q, Q: Query> QueryMut<'q, Q> {
     pub(crate) fn new(meta: &'q [EntityMeta], archetypes: &'q mut [Archetype]) -> Self {
+        // This looks like an ugly O(n^2) loop, but everything's constant after inlining, so in
+        // practice LLVM optimizes it out entirely.
+        Q::Fetch::for_each_borrow(|a, i, unique| {
+            if unique {
```
Comment (adamreichold) [inline src/query.rs:539]: One I think I did wonder is whether "properly" checking borrowing is necessary or whether just checking uniqueness of the component types would suffice. Borrowing the same component type twice immutably is a bit useless, but it is also possible using the dynamically checked variant. So it would be a strange API difference, but it would also simplify the implementation by avoid the uniqueness tag and the counter.

File: src/query.rs [hunk 2]
```diff
@@ -701,6 +737,15 @@ macro_rules! tuple_impl {
                 $($name::release(archetype);)*
             }
 
+            #[allow(unused_variables, unused_mut)]
+            fn for_each_borrow(mut f: impl FnMut(TypeId, usize, bool)) {
+                let mut counter = 0;
```
Comment (adamreichold) [inline src/query.rs:742]: Coming the borrow checking versus checking uniqueness below, wouldn't that counter need to be used for the whole type hierarchy? I think this way, we'll get examples like
```
((&i32, &mut i32), (&i32, &mut i32)) => ((0,1), (0,1))
```
instead of
```
((&u64, &mut i32), (&u64, &mut i32)) => ((0,1), (2,3))
```
and the above my actually check because `&mut i32` is positioned at `1` in both instances?

File: src/query.rs (hunk 1 above)
Comment (Ralith) [reply src/query.rs:539]: How would we avoid the counter in that case?

File: src/query.rs (hunk 2 above)
Comment (Ralith) [reply src/query.rs:742]: The callback is invoked for each individual borrow, and not for intermediate constructions like tuples. When tuples are nested, you end up with multiple counters, but an outer counter always ignores the output from the inner; you can see below that we discard the counter value passed in by the inner type. As a result, we should always get the second case.

File: src/query.rs (hunk 1 above)
Comment (adamreichold) [reply src/query.rs:539]: > it would also simplify the implementation by avoiding the uniqueness tag and the counter.

Actually, this would not be the case as we still need to avoid checking a component type against itself. But so we do need to resolve https://github.com/Ralith/hecs/pull/162#discussion_r628839322

File: src/query.rs (hunk 2 above)
Comment (adamreichold) [reply src/query.rs:742]: Maybe it would be simplest to not do any counting within `for_each_borrow` at all just keep the `i` and `j` counters as mutable variables on the stack of `QueryMut::new`? If `Q::Fetch::for_each_borrow` is guaranteed to always produce the same visitation order, keeping count could be done outside of it entirely.

File: src/query.rs (hunk 1 above)
Comment (adamreichold) [reply src/query.rs:539]: We cross posted here...

File: src/query.rs (hunk 2 above)
Comment (adamreichold) [reply src/query.rs:742]: > but an outer counter always ignores the output from the inner; you can see below that we discard the counter value passed in by the inner type.

Yes, now that you I mention it, I do see it. I would still argue that keeping the counters on the outer most layer in `QueryMut::new` would actually be the simplest way as it would avoid having to ignore any layer of counting.

Comment (Ralith) [reply src/query.rs]: Good catch; fixed.

**Comment by adamreichold** [comment]
LGTM

**Comment by Ralith** [comment]
Thanks!
